version: '3.8'
services:
  backend:
    build: ./backend
    ports: ['5000:5000']
  ml_service:
    build: ./ml_service
    ports: ['8000:8000']
  agent:
    build: ./agent
    volumes: ['./api_key.txt:/app/api_key.txt:ro']
    ports: ['7000:7000']
  frontend:
    build: ./frontend
    ports: ['3000:80']
