services:
  backend:
    build: ./backend
    image: petroagent-backend
    container_name: petroagent-backend
    ports: ["5000:5000"]
    restart: unless-stopped

  ml_service:
    build: ./ml_service
    image: petroagent-ml_service
    container_name: petroagent-ml_service
    ports: ["8000:8000"]
    restart: unless-stopped

  agent:
    build: ./agent
    image: petroagent-agent
    container_name: petroagent-agent
    depends_on:
      - ml_service
    environment:
      OPENAI_API_KEY_FILE: /run/secrets/openai_key
      OPENAI_MODEL: gpt-4.1-mini
      ML_SERVICE_URL: http://ml_service:8000
    secrets:
      - openai_key
    ports: ["7000:7000"]
    restart: unless-stopped

  frontend:
    build: ./frontend
    image: petroagent-frontend
    container_name: petroagent-frontend
    depends_on:
      - agent
    ports: ["3000:80"]
    restart: unless-stopped

secrets:
  openai_key:
    file: ./api_key.txt
