version: "3.9"

services:
  frontend:
    build: ./frontend
    container_name: petroagent_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
      - ml_service
      - agent
    networks:
      - petro
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: petroagent_backend
    environment:
      - DATA_DIR=/data
      - UVICORN_WORKERS=1
      - UVICORN_PORT=5000
    volumes:
      - data:/data
    expose:
      - "5000"
    networks:
      - petro
    restart: unless-stopped

  ml_service:
    build: ./ml_service
    container_name: petroagent_ml_service
    environment:
      - DATA_DIR=/data
      - UVICORN_WORKERS=1
      - UVICORN_PORT=8000
    volumes:
      - data:/data
    expose:
      - "8000"
    networks:
      - petro
    restart: unless-stopped

  agent:
    build: ./agent
    container_name: petroagent_agent
    environment:
      - OPENAI_API_MODEL=gpt-4o-mini
      - OPENAI_API_KEY_FILE=/run/secrets/openai_key
      - UVICORN_PORT=7000
    volumes:
      - ./api_key.txt:/run/secrets/openai_key:ro
    expose:
      - "7000"
    networks:
      - petro
    restart: unless-stopped

networks:
  petro:

volumes:
  data:
