version: '3.8'

services:
  backend:
    build: ./backend
    container_name: petroagent_backend
    ports:
      - "5000:5000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  ml_service:
    build: ./ml_service
    container_name: petroagent_ml_service
    ports:
      - "8000:8000"

  agent:
    build: ./agent_service
    container_name: petroagent_agent
    ports:
      - "7000:7000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  frontend:
    build: ./frontend
    container_name: petroagent_frontend
    ports:
      - "3000:80"
    depends_on:
      - agent
