services:
  backend:
    build: ./backend
    image: petroagent-backend
    container_name: petroagent_backend
    ports:
      - "5000:5000"
    restart: unless-stopped

  agent:
    build: ./agent
    image: petroagent-agent
    container_name: petroagent_agent
    environment:
      # Not required; we read api_key.txt directly. Left here for flexibility:
      # OPENAI_API_KEY: ""
      PYTHONUNBUFFERED: "1"
    volumes:
      - ./agent/api_key.txt:/run/secrets/openai_api_key:ro
    depends_on:
      - backend
    restart: unless-stopped

  ml_service:
    build: ./ml_service
    image: petroagent-ml_service
    container_name: petroagent_ml_service
    ports:
      - "8000:8000"
    volumes:
      - ./ml_service/data:/app/data
    environment:
      PYTHONUNBUFFERED: "1"
    depends_on:
      - backend
    restart: unless-stopped

  frontend:
    build: ./frontend
    image: petroagent-frontend
    container_name: petroagent_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
      - agent
      - ml_service
    restart: unless-stopped
