services:
  backend:
    build:
      context: ./backend
    container_name: petroagent-backend
    environment:
      - AGENT_URL=http://agent:7000
      - ML_URL=http://ml_service:8000
      - PYTHONUNBUFFERED=1
    ports:
      - "5000:5000"
    depends_on:
      - agent
      - ml_service

  agent:
    build:
      context: ./agent
    container_name: petroagent-agent
    environment:
      - OPENAI_KEY_FILE=/run/secrets/openai_key_file
      - PYTHONUNBUFFERED=1
    secrets:
      - openai_key_file
    ports:
      - "7000:7000"

  ml_service:
    build:
      context: ./ml_service
    container_name: petroagent-ml_service
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - models_data:/app/artifacts
      - uploads_data:/app/uploads
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    container_name: petroagent-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  models_data:
  uploads_data:

secrets:
  openai_key_file:
    file: ./api_key.txt
