version: "3.9"
services:
  frontend:
    build: ./frontend
    container_name: petroagent-frontend
    ports:
      - "3000:80"
    depends_on:
      - agent
      - ml_service
      - backend

  agent:
    build: ./agent
    container_name: petroagent-agent
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o-mini}
    expose:
      - "7000"

  ml_service:
    build: ./ml_service
    container_name: petroagent-ml_service
    volumes:
      - ./ml_service/outputs:/app/outputs
    expose:
      - "8000"

  backend:
    build: ./backend
    container_name: petroagent-backend
    expose:
      - "5000"
