version: "3.8"
services:

  agent:
    build:
      context: .
      dockerfile: Dockerfile.agent
    volumes:
      - ./api_key.txt:/app/api_key.txt:ro
      - ./data:/app/data
      - ./models:/app/models
      - ./plots:/app/plots
    ports:
      - "7000:7000"
    environment:
      - TZ=UTC

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - agent
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
