version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000

  ml_service:
    build: ./ml_service
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  agent:
    build: ./agent_service
    ports:
      - "7000:7000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - BACKEND_URL=http://backend:5000
      - ML_URL=http://ml_service:8000
    depends_on:
      - backend
      - ml_service

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - agent
      - backend
      - ml_service
