version: "3.8"
services:
  backend:
    build: ./backend
    container_name: petroagent_backend
    ports:
      - "5000:5000"
    env_file:
      - api_key.txt

  ml_service:
    build: ./ml_service
    container_name: petroagent_ml_service
    ports:
      - "8000:8000"

  agent:
    build: ./agent
    container_name: petroagent_agent
    ports:
      - "7000:7000"
    depends_on:
      - backend
      - ml_service

  frontend:
    build: ./frontend
    container_name: petroagent_frontend
    ports:
      - "3000:80"
    depends_on:
      - agent
